export type { components, operations, paths } from "./generated.js";

import type { components } from "./generated.js";

export type ApiActor = components["schemas"]["Actor"];
export type ApiErrorEnvelope = components["schemas"]["ErrorEnvelope"];
export type AdminDashboard = components["schemas"]["AdminDashboard"];
export type AdminAuditLog = components["schemas"]["AdminAuditLog"];
export type CatalogIp = components["schemas"]["CatalogIp"];
export type CatalogProduct = components["schemas"]["CatalogProduct"];
export type HomeCatalogSection = components["schemas"]["HomeCatalogSection"];
export type HomeCatalogSectionList = components["schemas"]["HomeCatalogSectionList"];
export type AdminHomeCatalogSection = components["schemas"]["AdminHomeCatalogSection"];
export type AdminHomeCatalogSectionList = components["schemas"]["AdminHomeCatalogSectionList"];
export type CreateHomeCatalogSectionInput = components["schemas"]["CreateHomeCatalogSectionInput"];
export type UpdateHomeCatalogSectionInput = components["schemas"]["UpdateHomeCatalogSectionInput"];
export type PublicKujiDeckSnapshot = components["schemas"]["PublicKujiDeckSnapshot"];
export type BindKujiSlotsInput = components["schemas"]["BindKujiSlotsInput"];
export type KujiSlotBindingResult = components["schemas"]["KujiSlotBindingResult"];
export type PaidKujiDrawRecovery = components["schemas"]["PaidKujiDrawRecovery"];
export type PaidKujiSelectionSnapshot = components["schemas"]["PaidKujiSelectionSnapshot"];
export type PaidGachaDrawCompletion = components["schemas"]["PaidGachaDrawCompletion"];
export type MediaUploadIntent = components["schemas"]["MediaUploadIntent"];
export type MediaMultipartPostUploadIntent = components["schemas"]["MediaMultipartPostUploadIntent"];
export type MediaRawPutUploadIntent = components["schemas"]["MediaRawPutUploadIntent"];
export type CommunityPost = components["schemas"]["CommunityPost"];
export type ExchangeListing = components["schemas"]["ExchangeListing"];
export type ExchangeOffer = components["schemas"]["ExchangeOffer"];
export type InventoryUnit = components["schemas"]["InventoryUnit"];
export type Inquiry = components["schemas"]["Inquiry"];
export type Notice = components["schemas"]["Notice"];
export type Report = components["schemas"]["Report"];
export type UserSummary = components["schemas"]["UserSummary"];
