import Link from "next/link";
import { adjustInventory } from "../../../../../lib/actions";
import { Feedback, PageHeader, ReasonField, ReturnTo, StatusBadge, formatDate, shortId } from "../../../../../components/operations";
import { adminApi } from "../../../../../lib/api";
import { requireCapability } from "../../../../../lib/auth";
import { can } from "../../../../../lib/capabilities";
import type { AdminInventoryDetail, SearchParams } from "../../../../../lib/admin-types";

export default async function InventoryDetailPage({ params, searchParams }: { params: Promise<{ productId: string }>; searchParams: Promise<SearchParams> }) {
  const { productId } = await params; const query = await searchParams; const session = await requireCapability("inventory.read");
  const item = await adminApi<AdminInventoryDetail>(`/v1/admin/commerce/inventory/${encodeURIComponent(productId)}`, { token: session.token });
  const mayAdjust = can(session.actor, "inventory.adjust"); const returnTo = `/commerce/inventory/${encodeURIComponent(productId)}`;
  return <>
    <PageHeader eyebrow="INVENTORY DETAIL" title="재고 상세" description="예약 하한과 추첨 경품 수용량을 넘는 조정은 거래 전체가 거부됩니다." actions={<Link className="button-link" href="/commerce/inventory">목록</Link>} />
    <Feedback searchParams={query} />
    <dl className="definition-grid"><div><dt>상품</dt><dd>{item.name}<br />{item.productId}</dd></div><div><dt>SKU/분류</dt><dd>{item.sku}<br />{item.category}</dd></div><div><dt>실재고</dt><dd>{item.onHand.toLocaleString("ko-KR")}</dd></div><div><dt>예약</dt><dd>{item.reserved.toLocaleString("ko-KR")}</dd></div><div><dt>판매 가능</dt><dd>{item.available.toLocaleString("ko-KR")}</dd></div><div><dt>재고 버전</dt><dd>v{item.version}</dd></div><div><dt>활성 상태</dt><dd><StatusBadge value={item.isActive} /></dd></div><div><dt>수정</dt><dd>{formatDate(item.updatedAt)}</dd></div></dl>
    {item.drawCapacity ? <section className="panel"><div className="panel-heading"><div><h2>유한 추첨 안전 경계</h2><p>남은 경품에서 미사용 추첨권을 뺀 수량보다 판매 재고를 높일 수 없습니다.</p></div></div><dl className="definition-grid"><div><dt>확률표</dt><dd>{shortId(item.drawCapacity.probabilityVersionId)}</dd></div><div><dt>무제한 풀</dt><dd>{item.drawCapacity.unlimited ? "예" : "아니요"}</dd></div><div><dt>남은 경품/추첨권</dt><dd>{item.drawCapacity.remainingPrizeUnits ?? "∞"} / {item.drawCapacity.outstandingEntitlements}</dd></div><div><dt>판매 상한</dt><dd>{item.drawCapacity.sellableUnits ?? "∞"}</dd></div></dl></section> : null}
    <section className="panel"><div className="panel-heading"><div><h2>수동 재고 조정</h2><p>{mayAdjust ? "최고 관리자 작업입니다. 증감과 전후 상태가 불변 원장과 감사 로그에 함께 남습니다." : "조회 전용입니다. 수동 재고 조정은 최고 관리자만 수행할 수 있습니다."}</p></div></div>{mayAdjust ? <form className="stack-form" action={adjustInventory}><input type="hidden" name="productId" value={item.productId} /><input type="hidden" name="expectedVersion" value={item.version} /><ReturnTo value={returnTo} /><label>실재고 증감<input type="number" name="deltaOnHand" min="-2147483647" max="2147483647" step="1" required placeholder="예: 2 또는 -1" /></label><ReasonField label="검수·조정 근거" /><div className="form-actions"><button className="danger">불변 조정 원장 기록</button></div></form> : null}</section>
    <section className="panel"><div className="panel-heading"><div><h2>조정 원장</h2><p>수동 조정 기록은 수정·삭제할 수 없습니다.</p></div></div>{item.adjustments.length === 0 ? <p className="muted">수동 조정 기록이 없습니다.</p> : <div className="data-panel"><table className="data-table"><thead><tr><th>증감</th><th>실재고 전→후</th><th>예약 전→후</th><th>운영자</th><th>사유</th><th>기록</th></tr></thead><tbody>{item.adjustments.map((entry) => <tr key={entry.id}><td>{entry.deltaOnHand > 0 ? "+" : ""}{entry.deltaOnHand}</td><td>{entry.beforeOnHand} → {entry.afterOnHand}</td><td>{entry.beforeReserved} → {entry.afterReserved}</td><td>{entry.adminNickname}</td><td>{entry.reason}</td><td>{formatDate(entry.createdAt)}</td></tr>)}</tbody></table></div>}</section>
    <section className="panel"><div className="panel-heading"><div><h2>최근 예약</h2><p>활성·확정·해제된 재고 예약을 최근 100건까지 표시합니다.</p></div></div>{item.reservations.length === 0 ? <p className="muted">예약 기록이 없습니다.</p> : <div className="data-panel"><table className="data-table"><thead><tr><th>주문</th><th>수량</th><th>상태</th><th>만료</th><th>해결</th></tr></thead><tbody>{item.reservations.map((entry) => <tr key={entry.id}><td><Link href={`/commerce/orders/${entry.orderId}`}>{shortId(entry.orderId)}</Link></td><td>{entry.quantity}</td><td><StatusBadge value={entry.status} /></td><td>{formatDate(entry.expiresAt)}</td><td>{formatDate(entry.resolvedAt)}</td></tr>)}</tbody></table></div>}</section>
  </>;
}
