import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import test from "node:test";

const directory = fileURLToPath(new URL(".", import.meta.url));
const project = "dabboba-prod", projectNumber = "123456789012", revisionName = "dabboba-api-00002-abc";
const image = `asia-northeast3-docker.pkg.dev/${project}/prod-images/dabboba-api:release-2026`;
const digest = `sha256:${"a".repeat(64)}`;
const account = `api-runtime@${project}.iam.gserviceaccount.com`;
const base = {
  PATH: "/usr/bin:/bin:/opt/homebrew/bin", DABBOBA_GCP_PROJECT_ID: project,
  DABBOBA_ARTIFACT_REPOSITORY: "prod-images", DABBOBA_IMAGE_TAG: "release-2026",
  DABBOBA_API_SERVICE_ACCOUNT: account, DABBOBA_GCS_BUCKET: "legacy-media",
  DABBOBA_DATABASE_SECRET: "api-database", DABBOBA_DATABASE_SECRET_VERSION: "7",
  DABBOBA_SESSION_PEPPER_SECRET: "session-pepper", DABBOBA_SESSION_PEPPER_SECRET_VERSION: "2",
  DABBOBA_WORKER_DATABASE_SECRET: "worker-database", DABBOBA_MIGRATION_DATABASE_SECRET: "migration-database",
  DABBOBA_SUPABASE_URL: "https://abcdefghijklmnopqrst.supabase.co", DABBOBA_WEB_ORIGINS: "https://app.example.com,https://www.example.com",
};
const supabase = {
  DABBOBA_MEDIA_STORAGE_PROVIDER: "supabase", DABBOBA_SUPABASE_STORAGE_BUCKET: "private-media",
  DABBOBA_SUPABASE_STORAGE_S3_ENDPOINT: `${base.DABBOBA_SUPABASE_URL}/storage/v1/s3`,
  DABBOBA_SUPABASE_STORAGE_S3_REGION: "ap-northeast-2",
};
for (const role of ["API", "WORKER"]) for (const key of ["SERVICE_KEY", "S3_ACCESS_KEY_ID", "S3_SECRET_ACCESS_KEY"]) {
  supabase[`DABBOBA_${role}_SUPABASE_STORAGE_${key}_SECRET`] = `${role.toLowerCase()}-${key.toLowerCase().replaceAll("_", "-")}`;
  supabase[`DABBOBA_${role}_SUPABASE_STORAGE_${key}_SECRET_VERSION`] = "3";
}
const modes = {
  gcs: {}, supabase: { ...supabase, DABBOBA_GCS_BUCKET: "" }, mixed: supabase,
  rollback: { ...supabase, DABBOBA_MEDIA_STORAGE_PROVIDER: "gcs" },
};
// Independent expected fixture, deliberately not generated by deployment helpers.
function expected(mode = "mixed") {
  const settings = { ...base, ...modes[mode] };
  const plain = {
    NODE_ENV: "production", API_SURFACE: "customer", LOG_LEVEL: "info", SUPABASE_URL: base.DABBOBA_SUPABASE_URL,
    SUPABASE_JWT_AUDIENCE: "authenticated", WEB_ORIGINS: base.DABBOBA_WEB_ORIGINS, PAYMENT_PROVIDER: "UNCONFIGURED",
    MEDIA_STORAGE_PROVIDER: settings.DABBOBA_MEDIA_STORAGE_PROVIDER || "gcs",
  };
  if (settings.DABBOBA_GCS_BUCKET) Object.assign(plain, { GCS_BUCKET: "legacy-media", GCS_PROJECT_ID: project });
  const secrets = { DATABASE_URL: { secret: "api-database", version: "7" }, SESSION_TOKEN_PEPPER: { secret: "session-pepper", version: "2" } };
  if (mode !== "gcs") {
    Object.assign(plain, { SUPABASE_STORAGE_BUCKET: "private-media", SUPABASE_STORAGE_S3_ENDPOINT: supabase.DABBOBA_SUPABASE_STORAGE_S3_ENDPOINT, SUPABASE_STORAGE_S3_REGION: "ap-northeast-2" });
    for (const key of ["SERVICE_KEY", "S3_ACCESS_KEY_ID", "S3_SECRET_ACCESS_KEY"]) secrets[`SUPABASE_STORAGE_${key}`] = { secret: `api-${key.toLowerCase().replaceAll("_", "-")}`, version: "3" };
  }
  return { plain, secrets };
}
function fixture(mode = "mixed", style = "v1", referenceStyle = "short") {
  const { plain, secrets } = expected(mode);
  const aliases = [];
  const env = Object.entries(plain).map(([name, value]) => ({ name, value }));
  for (const [name, ref] of Object.entries(secrets)) {
    let reference = ref.secret;
    if (referenceStyle === "project-id") reference = `projects/${project}/secrets/${reference}`;
    if (referenceStyle === "project-number") reference = `projects/${projectNumber}/secrets/${reference}`;
    if (referenceStyle === "alias") {
      reference = `lookup-${ref.secret}`;
      aliases.push(`${reference}:projects/${projectNumber}/secrets/${ref.secret}`);
    }
    env.push(style === "v1" ? { name, valueFrom: { secretKeyRef: { name: reference, key: ref.version } } }
      : { name, valueSource: { secretKeyRef: { secret: reference, version: ref.version } } });
  }
  const container = { image, env };
  const annotations = aliases.length ? { "run.googleapis.com/secrets": aliases.join(",") } : {};
  return style === "v1" ? { metadata: { name: revisionName, namespace: projectNumber, annotations }, spec: { serviceAccountName: account, containers: [container] } }
    : { name: `projects/${project}/locations/asia-northeast3/services/dabboba-api/revisions/${revisionName}`, serviceAccount: account, containers: [container], annotations };
}
function container(revision) { return (revision.spec || revision).containers[0]; }
function envEntry(revision, name) { return container(revision).env.find((entry) => entry.name === name); }
function run(script, mode = "mixed", revision = fixture(mode), extra = {}) {
  return spawnSync("/bin/bash", ["-c", `set -Eeuo pipefail
source "$1/_common.sh"
gcloud() {
  case "$1 $2 $3" in
    "run revisions describe") printf '%s\\n' "$TEST_REVISION" ;;
    "projects describe dabboba-prod") printf '%s\\n' '${projectNumber}' ;;
    "artifacts docker images") printf '%s\\n' '${digest}' ;;
    *) printf 'unexpected cloud call\\n' >&2; return 97 ;;
  esac
}
api_service_json() { printf '%s\\n' '${JSON.stringify({ status: { latestReadyRevisionName: revisionName, traffic: [{ revisionName, percent: 0, tag: "candidate-release-2026", url: "https://candidate-release-2026---dabboba-api-abc-an.a.run.app" }] } })}'; }
${script}`, "api-revision-test", directory], {
    env: { ...base, ...modes[mode], TEST_REVISION: JSON.stringify(revision), ...extra }, encoding: "utf8", timeout: 10_000,
  });
}
const gate = 'assert_api_candidate_release dabboba-api candidate-release-2026 0 dabboba-api-00002-abc';
function success(result) { assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`); return result.stdout.trim(); }
function rejected(result) {
  assert.notEqual(result.status, 0, result.stdout);
  assert.equal(result.stdout, "", "failed gate must emit no candidate URL/proof");
  assert.doesNotMatch(result.stderr, /unexpected cloud call/);
  assert.match(result.stderr, /approved API image, identity, environment or pinned secret references/);
}

test("API deployment maps and serialized flags exactly match independent GCS/Supabase/mixed/rollback fixtures", () => {
  for (const mode of Object.keys(modes)) {
    const values = expected(mode);
    assert.deepEqual(JSON.parse(success(run("api_plain_env", mode))), values.plain);
    assert.deepEqual(JSON.parse(success(run("api_secret_env", mode))), values.secrets);
    const plainFlag = success(run("api_plain_env | plain_env_flag", mode));
    assert.deepEqual(Object.fromEntries(plainFlag.slice(3).split("~").map((part) => [part.slice(0, part.indexOf("=")), part.slice(part.indexOf("=") + 1)])), values.plain);
    const secretFlag = success(run("api_secret_env | secret_env_flag", mode));
    assert.deepEqual(Object.fromEntries(secretFlag.split(",").map((part) => { const [key, ref] = part.split("="); const [secret, version] = ref.split(":"); return [key, { secret, version }]; })), values.secrets);
  }
});

test("central candidate gate accepts both official Revision shapes and only exact same-project secret identities", () => {
  for (const mode of Object.keys(modes)) for (const style of ["v1", "v2"]) for (const refs of ["short", "project-id", "project-number", ...(style === "v1" ? ["alias"] : [])]) {
    const revision = fixture(mode, style, refs);
    if (style === "v2") container(revision).image = image.replace(/:release-2026$/, `@${digest}`);
    container(revision).env.reverse();
    assert.match(success(run(gate, mode, revision)), /^https:\/\/candidate-release-2026---/);
  }
});

test("each plain configuration and pinned API secret is checked, including retained rollback storage", () => {
  for (const mode of Object.keys(modes)) {
    for (const key of Object.keys(expected(mode).plain)) {
      const revision = fixture(mode); envEntry(revision, key).value += "-mismatch";
      rejected(run(gate, mode, revision));
    }
    for (const key of Object.keys(expected(mode).secrets)) for (const field of ["name", "key"]) {
      const revision = fixture(mode); envEntry(revision, key).valueFrom.secretKeyRef[field] = field === "name" ? "other-secret" : "999";
      rejected(run(gate, mode, revision));
    }
  }
});

test("extra/missing/duplicate/plain-secret/hybrid configuration and alternate execution fail closed", () => {
  const mutations = [
    (r) => container(r).env.pop(), (r) => container(r).env.push({ name: "API_ENABLE_ADMIN", value: "true" }),
    (r) => container(r).env.push({ ...container(r).env[0] }),
    (r) => { const e = envEntry(r, "DATABASE_URL"); delete e.valueFrom; e.value = "raw-credential-do-not-print"; },
    (r) => { envEntry(r, "DATABASE_URL").value = ""; },
    (r) => { envEntry(r, "NODE_ENV").valueFrom = { secretKeyRef: { name: "anything", key: "1" } }; },
    (r) => { envEntry(r, "DATABASE_URL").valueFrom.secretKeyRef.optional = true; },
    (r) => { envEntry(r, "DATABASE_URL").valueFrom.secretKeyRef.key = "latest"; },
    (r) => { envEntry(r, "DATABASE_URL").valueFrom.secretKeyRef.key = 7; },
    (r) => { envEntry(r, "DATABASE_URL").valueFrom.secretKeyRef.key = "07"; },
    (r) => { r.spec.containers.push({ image, env: [] }); },
    (r) => { r.spec.serviceAccountName = `worker-runtime@${project}.iam.gserviceaccount.com`; },
    (r) => { r.metadata.name = "dabboba-api-00003-other"; },
    (r) => { r.metadata.namespace = "987654321098"; },
    (r) => { container(r).image = image.replace("prod-images", "foreign-repository"); },
    (r) => { container(r).command = ["node", "admin.js"]; },
    (r) => { container(r).args = ["admin"]; },
    (r) => { container(r).envFrom = [{ secretRef: { name: "unreviewed" } }]; },
    (r) => { container(r).volumeMounts = [{ name: "secret", mountPath: "/app/config" }]; },
    (r) => { r.spec.volumes = [{ name: "secret" }]; },
    (r) => { container(r).workingDir = "/admin"; },
    (r) => { container(r).sourceCode = {}; },
    (r) => { r.containers = structuredClone(r.spec.containers); },
    (r) => { r.spec = { template: { spec: r.spec } }; },
    (r) => { container(r).env = {}; },
  ];
  for (const mutate of mutations) {
    const revision = fixture(); mutate(revision);
    const result = run(gate, "mixed", revision); rejected(result);
    assert.doesNotMatch(result.stdout + result.stderr, /raw-credential-do-not-print/);
  }
});

test("foreign, unknown, duplicate and redirected aliases cannot mask a secret identity mismatch", () => {
  for (const reference of ["projects/foreign-project/secrets/api-database", "projects/999999999999/secrets/api-database", `projects/${project}/secrets/api-database/versions/7`, `projects/${project}//secrets/api-database`, "unknown-lookup", "../api-database"]) {
    for (const style of ["v1", "v2"]) {
      const revision = fixture("mixed", style); const entry = envEntry(revision, "DATABASE_URL");
      if (style === "v1") entry.valueFrom.secretKeyRef.name = reference; else entry.valueSource.secretKeyRef.secret = reference;
      rejected(run(gate, "mixed", revision));
    }
  }
  for (const annotation of [
    "api-database:projects/foreign-project/secrets/api-database",
    `api-database:projects/${project}/secrets/session-pepper`,
    `api-database:projects/${project}/secrets/api-database,api-database:projects/${project}/secrets/api-database`,
    `unused:projects/${project}/secrets/api-database`, `api-database:projects/${project}/secrets/unknown`,
    `api-database:projects/${project}/secrets/api-database,`, `api-database:projects/${project}/secrets/api-database\n`,
  ]) {
    const revision = fixture(); revision.metadata.annotations["run.googleapis.com/secrets"] = annotation;
    rejected(run(gate, "mixed", revision));
  }
  const valid = fixture(); valid.metadata.annotations["run.googleapis.com/secrets"] = `api-database:projects/${projectNumber}/secrets/api-database`;
  success(run(gate, "mixed", valid));
});

test("invalid expected input and unreadable project identity produce no URL even in nested substitutions", () => {
  for (const override of [{ DABBOBA_DATABASE_SECRET_VERSION: "latest" }, { DABBOBA_DATABASE_SECRET_VERSION: "7\n" }, { DABBOBA_DATABASE_SECRET: "api-database\n" }, { DABBOBA_DATABASE_SECRET_VERSION: "" }, { DABBOBA_API_SERVICE_ACCOUNT: "" }, { DABBOBA_SUPABASE_STORAGE_BUCKET: "Unsafe" }, { DABBOBA_WEB_ORIGINS: "https://app.example.com\n~API_SURFACE=admin" }]) {
    const result = run(`if result="$(${gate})"; then printf 'unexpected-success:%s' "$result"; else exit 1; fi`, "mixed", fixture(), override);
    assert.notEqual(result.status, 0); assert.equal(result.stdout, "");
  }
  const result = run(`expected_project_number() { return 1; }; ${gate}`);
  assert.notEqual(result.status, 0); assert.equal(result.stdout, "");
});

test("actual smoke and promotion scripts cannot probe or change traffic for mismatched candidate settings", () => {
  for (const script of ["smoke-api-candidate.sh", "promote-api-candidate.sh"]) {
    // Load the actual script with only unrelated preflight dependencies stubbed.
    // Keep the central comparator, image lookup, target resolution and postcheck real.
    const harness = `
source() { [[ "$1" == "$CLOUD_RUN_OPS_DIR/_common.sh" ]] || return 97; }
assert_database_release_attestation() { :; }
assert_gcloud_context() { :; }
assert_cloud_release_boundaries() { :; }
check_api_prerequisites() { :; }
assert_mutation_approval() { :; }
assert_api_invoker_iam_disabled() { :; }
assert_service_revisions_scale_to_zero() { :; }
export DABBOBA_API_CANDIDATE_TAG=candidate-release-2026
export DABBOBA_API_CANDIDATE_REVISION=${revisionName}
export DABBOBA_API_CANDIDATE_SMOKE_ATTESTATION=api-candidate:release-2026:candidate-release-2026:${revisionName}:PASSED
eval "$(declare -f gcloud | sed '1s/gcloud/gcloud_read_fixture/')"
gcloud() {
  if [[ "$1 $2 $3" == 'run services update-traffic' ]]; then
    printf 'TEST_TRAFFIC_MUTATION\\n' >&2; TEST_TRAFFIC=100
  elif [[ "$1 $2 $3" == 'run services describe' ]]; then printf '{}\\n'
  else gcloud_read_fixture "$@"; fi
}
api_service_json() {
  jq -cn --argjson percent "${"${TEST_TRAFFIC:-0}"}" '{status:{latestReadyRevisionName:"${revisionName}",traffic:[{revisionName:"${revisionName}",percent:$percent,tag:"candidate-release-2026",url:"https://candidate-release-2026---dabboba-api-abc-an.a.run.app"}]}}'
}
curl() {
  printf 'TEST_HTTP_PROBE\\n' >&2
  case "${"${@: -1}"}" in */v1/admin/products) printf 404 ;; *) printf 200 ;; esac
}
set --
builtin source "$CLOUD_RUN_OPS_DIR/${script}"
`;
    for (const mode of Object.keys(modes)) {
      const good = run(harness, mode, fixture(mode)); success(good);
      if (script.startsWith("smoke")) {
        assert.equal((good.stderr.match(/TEST_HTTP_PROBE/g) || []).length, 5);
        assert.match(good.stdout, /SMOKE_ATTESTATION=.*PASSED/);
      } else assert.equal((good.stderr.match(/TEST_TRAFFIC_MUTATION/g) || []).length, 1);
      for (const change of ["bucket", "secret-version", "surface"]) {
        const revision = fixture(mode);
        if (change === "bucket") envEntry(revision, mode === "gcs" ? "GCS_BUCKET" : "SUPABASE_STORAGE_BUCKET").value = "unexpected-bucket";
        else if (change === "secret-version") envEntry(revision, "DATABASE_URL").valueFrom.secretKeyRef.key = "99";
        else envEntry(revision, "API_SURFACE").value = "admin";
        const bad = run(harness, mode, revision); rejected(bad);
        assert.doesNotMatch(bad.stdout + bad.stderr, /TEST_HTTP_PROBE|TEST_TRAFFIC_MUTATION|SMOKE_ATTESTATION=.*PASSED/);
      }
    }
  }
});

test("deploy and all smoke/promotion checkpoints consume the central exact-configuration gate", () => {
  const deploy = readFileSync(new URL("deploy.sh", import.meta.url), "utf8");
  assert.match(deploy, /env_vars="\$\(api_plain_env \| plain_env_flag\)"/);
  assert.match(deploy, /secret_vars="\$\(api_secret_env \| secret_env_flag\)"/);
  for (const script of ["smoke-api-candidate.sh", "promote-api-candidate.sh"]) {
    const text = readFileSync(new URL(script, import.meta.url), "utf8");
    assert.match(text, /assert_api_candidate_release/);
    if (script.startsWith("smoke")) assert.ok(text.indexOf("api_candidate_smoke_target") < text.indexOf("probe_status \"$candidate_url/healthz\""));
    else assert.ok(text.indexOf("assert_api_candidate_release") < text.indexOf("gcloud run services update-traffic"));
  }
});
