import assert from "node:assert/strict";
import { readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import test from "node:test";
import { buildSupabaseApi } from "./build-supabase-api.mjs";

test("Supabase API artifact is pinned, bounded, and excludes unsupported provider runtimes", async () => {
  const output = join(tmpdir(), `dabboba-api-artifact-${process.pid}-${Date.now()}.js`);
  try {
    const result = await buildSupabaseApi(output);
    const code = await readFile(output, "utf8");
    assert.ok(result.bytes > 0 && result.bytes <= 5 * 1024 * 1024);
    assert.ok(result.inputCount > 0);
    assert.ok(result.externalImports.every((path) => path.startsWith("node:")));
    assert.match(code, /Generated by scripts\/build-supabase-api\.mjs/);
    assert.match(code, /Pino transports are unavailable in the Supabase API artifact/);
    assert.doesNotMatch(code, /createLocalEdgeApiIntegrationHarness|dabboba_edge_test|DABBOBA_EDGE_SMOKE_DATABASE_URL/);
    // buildSupabaseApi validates forbidden dependencies from esbuild metadata;
    // raw minified text can contain harmless symbol fragments such as node:vm.
  } finally {
    await rm(output, { force: true });
  }
});

test("Supabase API integration artifact is explicit and cannot replace the production default", async () => {
  const output = join(tmpdir(), `dabboba-api-integration-artifact-${process.pid}-${Date.now()}.js`);
  try {
    const result = await buildSupabaseApi(output, { mode: "integration" });
    const code = await readFile(output, "utf8");
    assert.ok(result.bytes > 0 && result.bytes <= 5 * 1024 * 1024);
    assert.ok(result.inputCount > 0);
    assert.ok(result.externalImports.every((path) => path.startsWith("node:")));
    assert.match(code, /dabboba_edge_test/);
  } finally {
    await rm(output, { force: true });
  }
});
